// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url:
      process.env["DATABASE_URL"] ||
      "postgres://2ea3e48c93133515f69a0b4682d270a80884c6fe8556fba72b181b2c792b474c:sk_-fmadhLM0glC2eeDC_RQN@db.prisma.io:5432/postgres?sslmode=require",
  },
});
